services:
  postgres:
    image: postgres:16.6-alpine@sha256:1d04b9ba1d4996401f2552b51beda8187f175c0645c091e4781134fc9c9a3eef
    environment:
      POSTGRES_USER: cache
      POSTGRES_PASSWORD: cache
      POSTGRES_DB: cache
    ports:
      - "127.0.0.1::5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cache -d cache"]
      interval: 1s
      timeout: 3s
      retries: 40
  redis:
    image: redis:7.4.2-alpine@sha256:02419de7eddf55aa5bcf49efb74e88fa8d931b4d77c07eff8a6b2144472b6952
    ports:
      - "127.0.0.1::6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 40
